SchoolManagementSystem2/Models/Enrollment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }
        public Nullable<decimal> Grade { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> LecturerId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual Lecturers Lecturers { get; set; }
    }
}

SchoolManagementSystem2/Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagementSystem2.Models;

namespace SchoolManagementSystem2.Controllers
{
    public class EnrollmentsController : Controller
    {
        private SchoolManagement_DBEntities db = new SchoolManagement_DBEntities();

        // GET: Enrollments
        public async Task<ActionResult> Index()
        {
            var enrollment = db.Enrollment.Include(e => e.Course).Include(e => e.Student).Include(e => e.Lecturers);
            return View(await enrollment.ToListAsync());
        }

        public PartialViewResult _enrollmentPartial(int? CourseID)
        {
            var enrollment = db.Enrollment.Where(q=>q.CourseID == CourseID)  //Filteration process
                .Include(e => e.Course)
                .Include(e => e.Student);
            return PartialView(enrollment.ToList());
        }

        // GET: Enrollments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = await db.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollments/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Course, "CourseID", "Title");
            ViewBag.StudentID = new SelectList(db.Student, "StudentID", "LastName");
            ViewBag.LecturerId = new SelectList(db.Lecturers, "Id", "First_Name");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "EnrollmentID,Grade,CourseID,StudentID,LecturerId")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollment.Add(enrollment);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Course, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Student, "StudentID", "LastName", enrollment.StudentID);
            ViewBag.LecturerId = new SelectList(db.Lecturers, "Id", "First_Name", enrollment.LecturerId);
            return View(enrollment);
        }

        [HttpPost]

        public async Task <JsonResult> AddStudent([Bind(Include = "CourseID,StudentID")] Enrollment enrollment)
        {
            var isEnrolled = db.Enrollment.Any(q => q.StudentID == enrollment.StudentID && q.CourseID == enrollment.CourseID);
            try
            {
                if (ModelState.IsValid && !isEnrolled)
                {
                    db.Enrollment.Add(enrollment);
                    await db.SaveChangesAsync();
                    return Json(new { IsSuccess = true, Message = "Student added Successfully" }, JsonRequestBehavior.AllowGet);
                }
                return Json(new {IsSuccess = false, Message = "Student not added Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                return Json(new {IsSuccess = false, Message = "Error: Contact Administrator" }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Enrollments/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = await db.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Course, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Student, "StudentID", "LastName", enrollment.StudentID);
            ViewBag.LecturerId = new SelectList(db.Lecturers, "Id", "First_Name", enrollment.LecturerId);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "EnrollmentID,Grade,CourseID,StudentID,LecturerId")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Course, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Student, "StudentID", "LastName", enrollment.StudentID);
            ViewBag.LecturerId = new SelectList(db.Lecturers, "Id", "First_Name", enrollment.LecturerId);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = await db.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Enrollment enrollment = await db.Enrollment.FindAsync(id);
            db.Enrollment.Remove(enrollment);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult GetStudents(string term)
        {
            var student = db.Student.Select(q => new
            {
                Name = q.FirstName + " " + q.LastName,
                Id=q.StudentID
            }).Where(q=> q.Name.Contains(term));
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagementSystem2/Views/Enrollments/Create.cshtml
@model SchoolManagementSystem2.Models.Enrollment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    $(function () {

        function LoadEnrollment(cid)
        {
            $.ajax({
                url: '@Url.Action("_enrollmentPartial", "Enrollments")',
                dataType: 'html',
                contentType: 'application/html; charset=utf-8',
                type: 'GET',
                data: {
                    CourseID: cid
                },
                success: function (data) {
                    $('#data').fadeOut().html(data).fadeIn();
                }
            });
        }

        var cid = $('#CourseID').val();
        LoadEnrollment(cid);

        $('#CourseID').change(function () {
            var cid = $('#CourseID').val();
            LoadEnrollment(cid);
            $("#Failed").fadeOut('fast');
            $("#Success").fadeOut('fast');
        });

        $("#Student_FirstName").autocomplete({
          source: function (request, response) {
                $.ajax({
                    url: "/Enrollments/GetStudents",
                    dataType: "json",
                    type: "POST",
                    data: {
                        term: request.term
                    },
                    success: function (data) {
                        console.log(data);
                        $("#Student_FirstName").val("");
                        response($.map(data, function (item) {
                            return { label: item.Name, value: item.Name, id: item.Id };
                        }))
                    }
                });
          },
            minLength: 2,
                select: function (event, ui) {
                    console.log(ui);
                    $("#StudentID").val(ui.item.id);
                }
        });
    });

    function Added(res)
    {
        if (res.IsSuccess)
        {
            $(function () {
                $("#Failed").fadeOut('fast');
                $("#Success").fadeIn('fast');

                var cid = $('#CourseID').val();
                $.ajax({
                    url: '@Url.Action("_enrollmentPartial", "Enrollments")',
                    dataType: 'html',
                    contentType: 'application/html; charset=utf-8',
                    type: 'GET',
                    data:
                    {
                        CourseID: cid
                    },
                    success: function (data)
                    {
                        $('#data').fadeOut().html(data).fadeIn();
                    }
                });

            })
        }
        else
        {
            Failed(res);
        }

    }

    function Failed(res)
    {
        $(function () {

            $("#Failed").fadeIn('fast');
            $("#Success").fadeOut('fast');


        })
    }


    function Failure()
    {
        $(function () {
            $("#Failed").fadeIn('fast');
        })
    }
</script>

<h2>Create</h2>

@using (Ajax.BeginForm("AddStudent","Enrollments",new AjaxOptions 
{
    HttpMethod="POST",
    OnSuccess="Added",
    OnFailure="Failure"

}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Enrollment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div id="Failed" class="alert alert-danger" style="display:none"> Something went wrong please input fields and try again.</div>

    <div id="Success" class="alert alert-success" style="display:none">
        Student added Successfully, view the table now.
    </div>



    <div class="form-group">
        <Label for="CourseID" class="control-label col-md-2"> Course </Label>

        <div class="col-md-10">
            @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <Label for="Student_FirstName" class="control-label col-md-2"> Student Name </Label>

        <div class="col-md-10">
            @Html.EditorFor(model => model.Student.FirstName, new { htmlattributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.StudentID)
            @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enroll Student" class="btn btn-success btn-block" />
        </div>
    </div>
</div>
 }
<hr />

<div id="data">

</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SchoolManagementSystem2/Views/Enrollments/Delete.cshtml
@model SchoolManagementSystem2.Models.Enrollment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lecturers.First_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lecturers.First_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolManagementSystem2/Views/Enrollments/Details.cshtml
@model SchoolManagementSystem2.Models.Enrollment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lecturers.First_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lecturers.First_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EnrollmentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SchoolManagementSystem2/Views/Enrollments/Edit.cshtml
@model SchoolManagementSystem2.Models.Enrollment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enrollment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EnrollmentID)

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LecturerId, "LecturerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LecturerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LecturerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SchoolManagementSystem2/Views/Enrollments/Index.cshtml
@model IEnumerable<SchoolManagementSystem2.Models.Enrollment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lecturers.First_Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Grade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lecturers.First_Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EnrollmentID }) |
            @Html.ActionLink("Details", "Details", new { id=item.EnrollmentID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EnrollmentID })
        </td>
    </tr>
}

</table>

SchoolManagementSystem2/Views/Enrollments/_enrollmentPartial.cshtml
@model IEnumerable<SchoolManagementSystem2.Models.Enrollment>

@if(Model.Count()<1)
 {
   <h1 class="text-center text-info" > NO ENROLLMENTS FOUND FOR THIS COURSE.</h1>
 }
     else 
     {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Grade)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Course.Title)
                </th>
                <th>
                    Student Name
                </th>

                <th> Action </th>
            </tr>

            @foreach (var item in Model)
             {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Grade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Student.FirstName) @Html.DisplayFor(modelItem => item.Student.LastName)
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.EnrollmentID })
                    </td>
                </tr>
             }

        </table>
     }